# Generated by Django 2.0.3 on 2018-04-15 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rollNo', models.CharField(max_length=15)),
                ('mobile', models.CharField(max_length=12)),
                ('complaintType', models.CharField(max_length=10)),
                ('hostelNo', models.CharField(max_length=5)),
                ('wing', models.CharField(max_length=5)),
                ('roomNo', models.CharField(max_length=4)),
                ('complaintTitle', models.CharField(max_length=100)),
                ('complaintDesc', models.CharField(max_length=350)),
            ],
        ),
    ]
